In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score

In [3]:
df = pd.read_csv("fertilizer_data.csv")
df

,crop,soil,N,P,K,fertilizer
0,Cotton,Red,116.124710,141.598852,154.946777,Vermicompost / Organic Manure
1,Potato,Red,72.747029,113.825316,146.624441,NPK 20-20-20
2,Potato,Loamy,23.607618,7.790695,191.227221,Urea
3,Potato,Sandy,133.505216,30.919941,195.352282,DAP (Di-Ammonium Phosphate)
4,Rice,Red,126.792270,110.120001,186.022138,Vermicompost / Organic Manure
...,...,...,...,...,...,...
3995,Tomato,Sandy,124.859257,45.791213,140.541836,NPK 20-20-20
3996,Rice,Clayey,85.510751,64.903284,57.536645,MOP (Muriate of Potash)
3997,Maize,Clayey,5.171290,10.144736,44.432458,Urea
3998,Maize,Red,59.069624,109.798450,176.158343,NPK 20-20-20
3999,Wheat,Black,52.931135,130.030943,170.672612,NPK 20-20-20

In [4]:
df.head()

,crop,soil,N,P,K,fertilizer
0,Cotton,Red,116.124710,141.598852,154.946777,Vermicompost / Organic Manure
1,Potato,Red,72.747029,113.825316,146.624441,NPK 20-20-20
2,Potato,Loamy,23.607618,7.790695,191.227221,Urea
3,Potato,Sandy,133.505216,30.919941,195.352282,DAP (Di-Ammonium Phosphate)
4,Rice,Red,126.792270,110.120001,186.022138,Vermicompost / Organic Manure

In [5]:
df.tail()

,crop,soil,N,P,K,fertilizer
3995,Tomato,Sandy,124.859257,45.791213,140.541836,NPK 20-20-20
3996,Rice,Clayey,85.510751,64.903284,57.536645,MOP (Muriate of Potash)
3997,Maize,Clayey,5.171290,10.144736,44.432458,Urea
3998,Maize,Red,59.069624,109.798450,176.158343,NPK 20-20-20
3999,Wheat,Black,52.931135,130.030943,170.672612,NPK 20-20-20

In [6]:
df.isnull().sum()

crop          0
soil          0
N             0
P             0
K             0
fertilizer    0
dtype: int64

In [7]:
df.describe()

                 N            P            K
count  4000.000000  4000.000000  4000.000000
mean     69.100120    75.373541   104.465404
std      40.212286    40.825582    58.255506
min       0.021167     5.016115     5.009508
25%      34.637561    39.925994    53.604171
50%      67.979039    75.787042   102.559809
75%     103.730134   111.740509   156.197187
max     139.984142   144.843071   204.968361

In [8]:
X=df[["crop","soil","N","P","K"]]
y=df["fertilizer"]

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
X = pd.get_dummies(X, columns=["crop","soil"])
y = pd.get_dummies(y, columns=["fertilizer"])

In [9]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [10]:
rf = RandomForestClassifier( n_estimators=100, random_state=42 )

In [11]:
rf.fit(X_train , y_train)

RandomForestClassifier(random_state=42)

In [12]:
y_pred = rf.predict(X_test)

In [13]:
print("train accuracy", rf.score(X_train,y_train))
print("test accuracy", rf.score(X_test,y_test))

train accuracy 1.0
test accuracy 0.995

In [15]:
import pickle
with open("fertilizer.pkl","wb")as file:
    pickle.dump(rf,file)

print("model saved")

model saved