In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [2]:
df=pd.read_csv("yield_data.csv")
df

,crop,area,rainfall,temperature,fertilizer_used,soil_quality,yield_tph
0,Cotton,4.472292,1689.636882,34.303563,80.893328,10.156759,1.748924
1,Tomato,18.804069,376.379491,10.718582,59.956049,75.990261,2.086515
2,Wheat,15.605731,1287.924939,20.083136,148.953898,22.392310,3.779234
3,Tomato,10.857162,1746.628441,41.776824,84.328711,26.553542,1.566908
4,Soybean,2.261004,466.069026,41.879696,121.651557,80.537245,2.663658
...,...,...,...,...,...,...,...
3995,Soybean,17.975091,1801.660383,36.840139,53.706692,63.531445,2.334490
3996,Rice,13.526043,1195.410667,29.889782,79.125468,14.433317,2.855958
3997,Tomato,2.198378,1751.626958,39.345908,264.168346,0.075204,1.834815
3998,Tomato,3.447988,1514.646849,14.967631,102.424597,33.932035,2.495011
3999,Rice,14.118699,243.506229,38.102531,192.964280,24.746667,1.481492

In [3]:
df.head()

,crop,area,rainfall,temperature,fertilizer_used,soil_quality,yield_tph
0,Cotton,4.472292,1689.636882,34.303563,80.893328,10.156759,1.748924
1,Tomato,18.804069,376.379491,10.718582,59.956049,75.990261,2.086515
2,Wheat,15.605731,1287.924939,20.083136,148.953898,22.392310,3.779234
3,Tomato,10.857162,1746.628441,41.776824,84.328711,26.553542,1.566908
4,Soybean,2.261004,466.069026,41.879696,121.651557,80.537245,2.663658

In [4]:
df.tail()

,crop,area,rainfall,temperature,fertilizer_used,soil_quality,yield_tph
3995,Soybean,17.975091,1801.660383,36.840139,53.706692,63.531445,2.334490
3996,Rice,13.526043,1195.410667,29.889782,79.125468,14.433317,2.855958
3997,Tomato,2.198378,1751.626958,39.345908,264.168346,0.075204,1.834815
3998,Tomato,3.447988,1514.646849,14.967631,102.424597,33.932035,2.495011
3999,Rice,14.118699,243.506229,38.102531,192.964280,24.746667,1.481492

In [5]:
df.isnull().sum()

crop               0
area               0
rainfall           0
temperature        0
fertilizer_used    0
soil_quality       0
yield_tph          0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   crop             4000 non-null   object
 1   area             4000 non-null   float64
 2   rainfall         4000 non-null   float64
 3   temperature      4000 non-null   float64
 4   fertilizer_used  4000 non-null   float64
 5   soil_quality     4000 non-null   float64
 6   yield_tph        4000 non-null   float64
dtypes: float64(6), object(1)
memory usage: 218.9+ KB

In [7]:
df.describe()

,area,rainfall,temperature,fertilizer_used,soil_quality,yield_tph
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,10.245251,1095.587547,25.724794,161.247891,49.199238,3.270893
std,5.638208,527.655041,9.210999,82.017900,28.570291,1.057288
min,0.503415,200.798509,10.003229,20.008218,0.016294,0.703365
25%,5.311552,633.394750,17.714712,87.738097,24.049724,2.506272
50%,10.231540,1093.563083,25.567257,161.704599,49.172456,3.138336
75%,15.134492,1557.065288,33.714020,235.011309,73.951816,3.943979
max,19.995207,1999.564883,41.995471,299.975354,99.942918,7.528042

In [8]:
X = df.drop("yield_tph", axis=1)
y = df["yield_tph"]

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()
X["crop"] = le.fit_transform(X["crop"])

In [11]:
X_train, X_test, y_train, y_test = train_test_split( X,y,test_size=0.2,random_state=42)

In [12]:
rf = RandomForestRegressor(n_estimators=100,random_state=42)

In [13]:
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [14]:
y_pred = rf.predict(X_test)

In [15]:
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

R2 Score: 0.8708117589655109

In [16]:
print("train accuracy", rf.score(X_train,y_train))
print("test accuracy", rf.score(X_test,y_test))

train accuracy 0.9828117675909348
test accuracy 0.8708117589655109

In [17]:
import pickle
with open("yield.pkl","wb")as file:
    pickle.dump( rf, file)

print("model saved")

model saved

In [19]:
import joblib
joblib.dump(rf, "yield.pkl", compress=3)

['yield.pkl']